# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbf35f10112fe401d6bbee9ff11a9d28ff6014225961ae2efacbd79a1ecfd3f93fb50054a3f686205997af0fc3207ef03646ca0736d48f434733be0166168d85

test:
  secret_key_base: 8ad06d39294bc9305aa8b3e0d49eec15d81391c0da44a3f1a8a291065e49f77fc591f64fd3242408ef66e66e5e792e19eb608e652d1545ac502dd3fabef6989a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
